language: ruby
rvm:
- 2.1.0
cache:
- bundler
script: bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: BGyKgGp16e4R/+25m8SegxryYSNT+Ln6L6HZ/r00BaFCYizrcOhJyEYi/k8tLKJrlCEkEhnNI66SVrexCJIrjpDsyonpj2HfvyzDPWdhYIAVwdVYp0pe/Vqg6ZyVQusHLDSNsoS+Zy7lbUA8wXs+G8BNqkypl5blgJ/Wc5KRqDw=
