language: ruby
rvm:
- 1.9.3
script: bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: Dnk8cH1ttkxQrNAxW9o80RG6Zwb9REBkyMbziFWAfqqIJpaTlnw50FdLKi4NXn3mohPJrggQFgZrxARZN8GlBZ/1/pTPPvk9Mip+BizpGOxnhrm0Yt3vWeAwQ0kA7C1pK6xjXcKqtpkkw5FOgTlONlwBvURy3oLQ5Eo91tr5Nx4=
